version: "3"

dotenv: [".env"]

tasks:
  build:
    desc: Build the Stack binary
    cmds:
      - go build -o stack .

  dev:
    desc: Run Stack on port 8080
    cmds:
      - go run main.go

  build-and-run:
    desc: Build and run Stack
    cmds:
      - task: build
      - ./stack
